### ISSUE TITLE
Applet differs from q4osXpack bundled binary

### ISSUE THREAD

**Issue by q4osteam** [seb3773/actioncenter-kicker-applet#9]
We have built debian package from the source. The applet works, but it apparently differs from the system where q4osXpack has been installed. It's in French by default and button actions don't behave the same way. How could we compile actioncenter applet to get exactly the same result ?
![actioncenter1](https://github.com/user-attachments/assets/38bc3a98-0e57-44a8-a9ec-d4c7814b4b22)

**Comment by seb3773** [comment]
Yes, the version included in q4osxpack is not this one. This version was modified by blu256 who tried to help me improving it (convert to cmake build system and other modifications) but there is a bug in displaying the brightness button and it is for now in "standby"... The version in q4osxpack is this one: https://github.com/seb3773/actioncenter-kicker-applet-legacy
(the initial code I wrote) 

I didn't create a .deb but I can do it if you want, for now the files used for installation of the applet are:

q4osXpack/theme/actioncenter_libs.tar.gz      >   contains libs for x64,i386 & armhf
q4osXpack/theme/actioncenter_assets.tar.gz      >     the buttons bitmaps and scripts localized (en,de,fr,ru)
q4osXpack/theme/actioncenter_applet.desktop.tar.gz   > .desktop file

An improvement will be to draw the text on buttons instead of using "pre made" buttons with localized text, I will work on it as soon as possible to modify this, but as I said I'm not good to code graphical ui and I'm not goot with tqt3 too :p (although I'm learning) that's why maybe the code is not very well written...

**Comment by q4osteam** [comment]
Thanks for the info, we will try to compile the legacy actioncenter. We don't need deb package at the moment, however it would be convenient to "debianize" the project - so creating debian directory for anyone to be able to easily compile the project from source.
